### ISSUE TITLE
Support for 3gp

### ISSUE THREAD

**Issue by medez** [sindresorhus/file-type#105]
Hello, 

Could you add the support of 3gp files ? For information, 3gp files are identified by the string "ftyp3gp4" at the offset 3.

Best regards,
Seb

**Comment by sindresorhus** [comment]
Submit a pull request with tests and docs (Look at commits for previous additions to see what to do).

**Comment by dominic-p** [comment]
It looks like 3gp is [already supported](https://github.com/sindresorhus/file-type/blob/v7.5.0/index.js#L337). However, the signature may be slightly off.

[According to Wikipedia](https://en.wikipedia.org/wiki/List_of_file_signatures), the signature for 3gp is: `66 74 79 70 33 67` at offset 4.

But, the detection code currently checks for `0x66, 0x74, 0x79, 0x70, 0x33, 0x67, 0x70, 0x34`. This works for most 3pg files I have seen, but at least one I tested had `0x35` instead of `0x34` in the last position, causing the detection to fail. Maybe we should make the signature a little more lenient?

I'd be happy to submit a PR if that would help, but my recommendation would simply be to remove the last 2 numbers from the signature.

**Comment by medez** [comment]
Hi, dominic-p,
Please submit a pull request, I really no have any time to do it.
