### ISSUE TITLE
stream method does not rewind stream after reading

### ISSUE THREAD

**Issue by intellix** [sindresorhus/file-type#216]
**Node:** 10.16, 11.15, 12

Originally I had a 20kb+ image or so and was wondering why image uploads to S3 weren't showing properly. Eventually narrowed it down to usage of:
```ts
await fileType.stream(stream);
```

After narrowing down my example massively to a simple `fs.createReadStream` and a 1kb image and trying different node versions it's quite obvious:

Simple 1kb image:
![thatch](https://user-images.githubusercontent.com/1162531/58562784-8155d980-825c-11e9-9726-f624e7d87650.jpg)

If you comment out the `await fileType.stream(stream);` then it'll print to stdout:
```ts
const fs = require('fs');
const fileType = require('file-type');

async function main() {
  const stream = fs.createReadStream('thatch.jpg');
  const ft = await fileType.stream(stream);
  console.log(ft.fileType);
  stream.pipe(process.stdout);
}

main();
```

**Comment by intellix** [comment]
Ignoring PassThrough completely works for me... but I'm a bit of a Stream noob so I'm not sure what it's there for and need to read more ;o

```ts
fileType.stream = readableStream => new Promise((resolve, reject) => {
	readableStream.once('readable', () => {
		const chunk = readableStream.read(module.exports.minimumBytes) || readableStream.read();
		try {
			readableStream.fileType = fileType(chunk);
		} catch (error) {
			reject(error);
		}

		readableStream.unshift(chunk);
		resolve(readableStream);
	});
});
```

**Comment by sindresorhus** [comment]
// @bencmbrook

**Comment by juona** [comment]
Aren't you supposed to use `ft` in your further pipes, rather than the original stream? I.e. do `ft.pipe(process.stdout)` instead of `stream.pipe(process.stdout)`.

Source: I use this to upload large compressed tarballs. After type detection I am able to successfully decompress and extract the upload, so it appears to be working correctly _if_ used this way.

**Comment by intellix** [comment]
Damn... you're right. I just thought it was ruining my original stream. I guess it's not meant to fix the original:

Confirmed to work:
```
const fs = require('fs');
const fileType = require('file-type');

async function main() {
  const stream1 = fs.createReadStream('/Users/dominicwatson/Pictures/thatch.jpg');
  const stream2 = await fileType.stream(stream1);
  console.log(stream2.fileType);
  stream2.pipe(process.stdout);
}

main();
```

**Comment by bencmbrook** [comment]
@intellix glad this was resolved and thanks @juona. 

Confirming that the returned stream is what should get used. The original stream reads in data to detect the underlying filetype and returns a new PassThrough stream in the original unread state. Since the first stream has already been read to detect the filetype, it shouldn't be used. I tried rewinding the original stream, but that unfortunately created more problems than it solved. Cheers!
