### ISSUE TITLE
100% cpu with 177.3 MiB zip

### ISSUE THREAD

**Issue by thisconnect** [sindresorhus/file-type#226]
I accidentally passed a bigger buffer to fileType, 
i.e. this file https://imagemagick.org/download/windows/releases/ImageMagick-6.9.10-33.zip

Seems to hang iterating through the whole buffer here: 
https://github.com/sindresorhus/file-type/blob/a1da90b2c1121377e47f5dec1f1ce263b5b4f31f/index.js#L275
Is that expected?

It doesn't hang of corse if I pass just a subarray 
`filetype(body.subarray(0, filetype.minimumBytes))` then everything works and `{ ext: 'zip', mime: 'application/zip' }` is returned

**Comment by sindresorhus** [comment]
// @jacor84

**Comment by thisconnect** [comment]
I am currently only passing a subarray length of minimumBytes, but wonder if there would be any benefit if I pass more than that, especially with application/zip data

**Comment by jacor84** [comment]
I agree that this algorithm could be optimized for larger files. Expecially the `findNextZipHeaderIndex` function, which is using `Array.findIndex(function)`. I will try to find a good solution and test for performance during the next few days. One idea is to use `Buffer. indexOf()` since we are looking for consecutive bytes.
