### ISSUE TITLE
minimumBytes was not properly deprecated, breaking change

### ISSUE THREAD

**Issue by arciisine** [sindresorhus/file-type#328]
in 14.0.0 (a major release), minimumBytes was removed (not deprecated) (#319 ).  

This has had a breaking change on code that relies on that constant being exposed.    A proper deprecation path would be appreciated.

**Comment by sindresorhus** [comment]
It's still there: https://github.com/sindresorhus/file-type/blob/b280b9104e58e69a6ab85f0aaed9b127948fc118/core.js#L60

**Comment by Borewit** [comment]
> It's still there:
> 
> https://github.com/sindresorhus/file-type/blob/b280b9104e58e69a6ab85f0aaed9b127948fc118/core.js#L60-L63

The usage of `minimumBytes` (which is private value now) does not make any sense in that line, it should be 512 or the `length: 512` should be removed.

You are right @arciisine, it was already obsolete since (#286, [v13.0.0](https://github.com/sindresorhus/file-type/releases/tag/v13.0.0)), and now it has been removed.

You can pass any number of bytes @arciisine. There is no special number of bytes anymore, other then the total number of bytes of the file you wish to analyze.

**Comment by arciisine** [comment]
Just to reiterate the PR indicated it was deprecated but it was actually
removed from the public API and is no longer available to use.


I plan on updating my code to not rely on that constant, but the wording of
the change may surprise others as well.

**Comment by Borewit** [comment]
> I plan on updating my code to not rely on that constant, but the wording of
the change may surprise others as well.

Very good. Try to use [fromFile()](https://github.com/sindresorhus/file-type#filetypefromfilefilepath) if possible. I updated the title of #319 and release description of [v14.0.0](https://github.com/sindresorhus/file-type/releases/tag/v14.0.0).
