### ISSUE TITLE
Very small file (11 byte)

### ISSUE THREAD

**Issue by 99ACA** [sindresorhus/file-type#341]
Expected - return undefined 
Bug - got exception  'End-Of-Stream'
Scenario - Sent very small file (11 bytes), the file data sent as stream.

`let fileType = await FileType.fromStream(passThroughStream)`

**Comment by sindresorhus** [comment]
Can you confirm you're on the latest version? This should have been fixed in https://github.com/sindresorhus/file-type/commit/90a213d7b08460516b5841f5ef9947b09c8f5de1.

**Comment by LinusU** [comment]
Empty streams still trigger "End-Of-Stream" error:

https://runkit.com/embed/so22y64gvz7l

**Comment by sindresorhus** [comment]
// @bencmbrook

**Comment by bencmbrook** [comment]
```diff
const { PassThrough } = require('stream')
const fileType = require('file-type')

const stream = new PassThrough()
- const result = fileType.fromStream(stream)
+ const result = fileType.stream(stream)
stream.end()

await result
```

Changing this to `fileType.stream` fixes it.

I didn't write `.fromStream`, but if the goal of that is just to return the filetype only, then I'd recommend we just have it wrap `.stream`

**Comment by LinusU** [comment]
Hmm, it seems like the `fromStream` and `stream` from the outside looks quite similar, and it's a bit confusing as a consumer of the library.

In my use case, I do not want to modify the readable stream by adding a `fileType` property to it, I just want to have a Promise that resolves with the file type.

Is there any reason why `.stream` isn't internally implemented as:

```js
async function stream(readableStream) {
  const fileType = await fromStream(readableStream)
  return Object.assign(readableStream, { fileType })
}
```

That way the logic can be shared in `fromStream`, instead of having two different implementations, or am I missing something? 🤔 

I'd be open to submitting a PR for this btw ☺️

**Comment by Borewit** [comment]
@bencmbrook
> I'd recommend we just wrap it around my .stream method rather than have separate stream logic.

I don't think that is possible. `stream()` is essentially using the old style 4k limit way of parsing. An attempt to address that has been done in #300, but there is no easy solution for this. `fromStream()` does not suffer from the 4k detection limit.

**Comment by Borewit** [comment]
Issue presumably caused in strtok3: Borewit/strtok3#206
