### ISSUE TITLE
Why is detecting file type from buffer async?

### ISSUE THREAD

**Issue by zadam** [sindresorhus/file-type#410]
Hi, I'm wondering why is `FileType.fromBuffer(buffer)` async - i.e. returns Promise? 

Reading buffer seems naturally synchronous since there's no I/O involved.

**Comment by sindresorhus** [comment]
Because the core parser is made with a stream which is async. It would indeed be nice to have synchronous support too.

**Comment by Borewit** [comment]
Indeed, due to the common functions and code which, depending under the underlying media, require asynchronous behavior. it not feasible to split these into asynchronous and synchronous. Unfortunately there is no way, or at least as far as I know, to convert asynchronous into synchronous behavior. Is the asynchronous an issue, knowing it resolves immediate?

**Comment by zadam** [comment]
Thank you for the explanation.

> Is the asynchronous an issue, knowing it resolves immediate?

In some cases yes. As an example [transaction](https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/api.md#transactionfunction---function) function from better-sqlite3 needs a synchronous callback, I believe it won't work for async callbacks even if it resolves immediately. Of course there are workarounds possible, but they often result in more complex code.

But I understand the engineering challenges in making this call synchronous.

**Comment by Borewit** [comment]
I didn't directly thought about such a case. In case of a transaction, you don''t want to introduce any unnecessary delay. Even if there an expensive synchronous function is probably better to execute outside the transaction. Nevertheless, I understand it maybe bit inconvenient some cases.
