### ISSUE TITLE
`SyntaxError: Cannot use import statement outside a module` When running in Jest

### ISSUE THREAD

**Issue by EricHasegawa** [sindresorhus/file-type#623]
I'm using file-type `^19.0.0`, I have a line in my file `import { fileTypeFromBuffer } from 'file-type'` that causes this error when I run jest over this file.
` ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as strtok3 from 'strtok3';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module`

Here's an identical issue on Stack Overflow from a year ago https://stackoverflow.com/questions/74917081/jest-error-while-trying-to-use-with-the-file-type-module-how-can-i-fix-cannot

**Comment by sindresorhus** [comment]
This is a problem with your Jest config, not this package.

**Comment by ym-project** [comment]
Personally I resolve this problem next way:

#### Requirements:
- version of file-type is 21.0.0
- use babel-jest as file transformer

#### Error "Cannot find module 'file-type' from 'your-file.ts'"
Add to your jest config:
```js
module.exports = {
	// ... here your existed rules
	moduleNameMapper: {
		// ... here your existed rules
		'^file-type$': '<rootDir>/node_modules/file-type/core.js',
	},
};
```

#### SyntaxError: Cannot use import statement outside a module
By default jest transformer doesn't touch files inside node_modules, we need to transform all dependencies that `file-type` uses.
Dependencies such as: file-type, strtok3, token-types, @tokenizer/inflate, uint8array-extras.
```js
module.exports = {
	// ... here your existed rules
	transformIgnorePatterns: [
		// ... here your existed rules
		'node_modules/(?!(file-type|strtok3|token-types|@tokenizer/inflate|uint8array-extras)/)',
	],
};
```

#### TypeError: globalThis.TextDecoder is not a constructor
Now we need to redefine `globalThis.TextEncoder` and `globalThis.TextDecoder`
If must to create setup file if you don't have it before. Inside your jest config:
```js
module.exports = {
	// ... here your existed rules
	setupFilesAfterEnv: ['<rootDir>/path/to-your-file/setup.ts'],
};
```
And inside setup file you write:
```ts
import { TextDecoder, TextEncoder } from 'util';

globalThis.TextEncoder = TextEncoder;
// @ts-expect-error fix error "TypeError: globalThis.TextDecoder is not a constructor"
globalThis.TextDecoder = TextDecoder;
```

If you have typescript error "Type 'typeof TextDecoder' is not assignable to type" in your setup file, jest add ignore comment:
```ts
import { TextDecoder, TextEncoder } from 'util';

globalThis.TextEncoder = TextEncoder;
// @ts-expect-error fix error "TypeError: globalThis.TextDecoder is not a constructor"
globalThis.TextDecoder = TextDecoder;
```

**Comment by Borewit** [comment]
Asking imaginary friends to upvote your issue and downvote responses you don’t like doesn’t make your argument more valid.

To clarify: Jest’s support for ESModules is still experimental, as noted in their official documentation: https://jestjs.io/docs/ecmascript-modules. This clearly indicates that loading ESModules is not fully supported out of the box.

You're attempting to test code using ESModules in Jest, which isn’t fully stable yet, and then blaming the file-type module, a well-maintained ESM module, used in over 2 million open-source GitHub projects, for the failure. That’s not the most plausible root cause.

Hence I second @sindresorhus :
>This is a problem with your Jest config, not this package.

I admit my original answer on Stack Overflow ([link](https://stackoverflow.com/questions/74917081/jest-error-while-trying-to-use-with-the-file-type-module-how-can-i-fix-cannot)) wasn’t the best, it was slightly off-topic and didn’t fully address the specific issue. I updated it, in line with this answer.

I don’t typically use Jest, but out of curiosity, I gave it a try. With a few adjustments, I managed to get dynamic import() to work in a Jest environment.

1. Critical portions are, in `package.json`:
    ```json
    "jest": {
      "transform": {}
     }
    ```
2. Enable Node option `--experimental-vm-modules` in `package.json`:
     ```json
    "scripts": {
      "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js"
   ```
3. Ensure you declare the `export`, even if if you import locally in Jest:

in the `package.json`:

```json
{
  "name": "jest-esm",
  "version": "0.1.0",
  "description": "JEST ESM",
  "keywords": [
    "Jest",
    "ESM"
  ],
  "license": "MIT",
  "author": "Borewit",
  "type": "commonjs",
  "main": "index.js",
  "scripts": {
    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js"
  },
  "devDependencies": {
    "jest": "^30.0.5"
  },
  "dependencies": {
    "file-type": "^21.0.0"
  },
  "jest": {
    "transform": {}
  }
}
```

`whichFile.js`
```js
async function whichFile() {
    // Dynamic import of a pure ESM module
    const { fileTypeFromBuffer } = await import('file-type'); 

    // This is the header of a PNG file
    const buffer = Buffer.from([
        0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
        0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    ]);

    return fileTypeFromBuffer(buffer);
}

module.exports = { whichFile }; // Required, Jest will fail without
```

`whichFile.test.js`
```js
const {whichFile} = require('./which-file');

test('adds 1 + 2 to equal 3', async () => {
    const fileType = await whichFile();
    expect(fileType.ext).toEqual('png');
});
```

Outputs:
```
 PASS  ./which-file.test.js
  √ adds 1 + 2 to equal 3 (28 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.182 s, estimated 1 s
Ran all test suites.
```
