### ISSUE TITLE
Support for Adobe Illustrator file ai

### ISSUE THREAD

**Issue by NickNaso** [sindresorhus/file-type#64]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/file-type/issues/64)

Hi,
i need to add the support for ai files. 
Thanks in advance.
Nick

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Submitted pull Requests
- [#323 src: Add support for AI files (Adobe Illustrator)](https://issuehunt.io/r/sindresorhus/file-type/pull/323)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/file-type/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by kevva** [comment]
It's a little bit tricky to detect `ai` files just by looking at their magic numbers since `pdf` files has the same magic numbers.

**Comment by t1st3** [comment]
@kevva 
it seems even more complicated, since `.ai` may be based either on `pdf` or `eps` (see [AI on Wikipedia](https://en.wikipedia.org/wiki/Adobe_Illustrator_Artwork)).
Furthermore, [filext.com](http://filext.com/file-extension/AI) gives a file signature for `.ai` files (25 21 50 53 2D), which is the beginning of the signature for `.eps` files on [Gary Kessler's file signature list](http://www.garykessler.net/library/file_sigs.html), while, on that list, Gary makes no distinction between `.pdf` and `.ai` in terms of file signatures.

**Comment by sindresorhus** [comment]
Not even `file` (which is the best one) is not able to detect it correctly:

```
❯ file logo.ai
logo.ai: PDF document, version 1.5
```
