### ISSUE TITLE
fileTypeFromFile are not defined in browser.d.ts

### ISSUE THREAD

**Issue by romanhrynevych** [sindresorhus/file-type#640]
Why I can't use this function inside my front-end app to define what mime type is file?

<img width="937" alt="image" src="https://github.com/sindresorhus/file-type/assets/82209198/2e209f86-6a82-4004-bef1-05ed4adfaba0">

**Comment by Borewit** [comment]
Because `fileTypeFromFile` is used to access files on you local file system, which is only possible via [Node.js file sytem API](https://nodejs.org/api/fs.html).

If you want to read a [File](https://developer.mozilla.org/en-US/docs/Web/API/File) (a File you uploaded in a browser environment), you can use [`fileTypeFromBlob(blob)`](https://github.com/sindresorhus/file-type?tab=readme-ov-file#filetypefromblobblob).

This could be better documented in the README, please keep this issue open until that is clearly captured.
