### ISSUE TITLE
Detecting a pptx taking a very long time

### ISSUE THREAD

**Issue by scottdoc** [sindresorhus/file-type#688]
### Description

Hello,

I have this library running in AWS via S3 in order to detect uploaded file types. I use fileTypeFromTokenizer.

When it came to a specific pptx file, it seemed to hang and take a very long time. Several minutes were not enough. 

I eventually got it to correctly detect the type after 7 minutes.

Looking at the code I could see it was going through and getting zip headers. This was a relatively large PPT (17MB) with more than 20 photos bundled into it. Big, but not abnormally big. 

Each one was downloaded like this:

```
{
  compressedSize: 631,
  uncompressedSize: 631,
  filenameLength: 16,
  extraFieldLength: 0,
  filename: '[trash]/0000.dat'
}
{
  compressedSize: 0,
  uncompressedSize: 0,
  filenameLength: 16,
  extraFieldLength: 0,
  filename: 'docProps/app.xml'
}
{
  compressedSize: 0,
  uncompressedSize: 0,
  filenameLength: 24,
  extraFieldLength: 0,
  filename: 'ppt/fonts/font23.fntdata'
}
... more fonts 
{
  compressedSize: 0,
  uncompressedSize: 0,
  filenameLength: 20,
  extraFieldLength: 0,
  filename: 'ppt/media/image1.png'
}
... more images
```

It finally got to 
```
{
  compressedSize: 0,
  uncompressedSize: 0,
  filenameLength: 33,
  extraFieldLength: 0,
  filename: 'ppt/notesMasters/notesMaster1.xml'
}
```

And then was able to see it ended in ".xml" and reported back the content type.

I really know very little about detecting Mime types, so forgive me if this is completely wrong, but I was wondering if the filename "ppt/*" was enough to declare the file type and shortcut downloading everything? Similar to a shortcut provided for xlsx? 

I will put up a PR if I can.

Thanks.

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### ESM (ECMAScript Module) Requirement Acknowledgment

- [X] My project is an [ESM project](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) and my `package.json` contains the following entry: `"type": "module"`.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

Resolves #688

**Comment by Borewit** [comment]
In many cases, the [tokenizer-s3](https://github.com/Borewit/tokenizer-s3) library can significantly enhance the speed of S3 file detection.

I am not in favor of relying solely on matching the `ppt/` path, as this approach feels more like an educated guess rather than a reliable method for identifying a `pptx` file.

A more robust solution might involve extracting and analyzing the `docProps/app.xml` file, which offers a much more specialized detection mechanism. However, this approach requires decompression and XML parsing, which adds complexity. Consequently, it might be better to delegate this functionality to an add-on for Office or zipped formats.

**Comment by Borewit** [comment]
Proof of concept:

```js
import * as unzipper from 'unzipper';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import { DOMParser } from 'xmldom';
import xpath from 'xpath';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixturePath = join(__dirname, '..', 'fixture');

async function extractFileMimetype(fixture) {
  const directory = await unzipper.Open.file(join(fixturePath, fixture));

  const file = directory.files.find(file => file.path === '[Content_Types].xml');

  // Extract and read the file content
  const xmlContent = (await file.buffer()).toString('utf8');

  // Parse [Content_Types].xml
  const doc = new DOMParser().parseFromString(xmlContent, 'application/xml');

  // Define XPath expression to find <Override> elements
  const overrides = xpath.select('//*[local-name()="Override"]', doc);

  // Find the first Override element where ContentType ends with .main+xml
  for (const override of overrides) {
    const contentType = override.getAttribute('ContentType');
    if (contentType && contentType.endsWith('.main+xml')) {
      return contentType.slice(0, -9);  // Remove last 8 characters (".main+xml")
    }
  }

  return 'No matching ContentType found';
}

async function testTypes() {
  const fixtures = [
    'fixture.docx',
    'fixture2.pptx',
    'fixture-vsdx.vsdx',
    'fixture-vstx.vsdx',
    'file_example_XLSX_10.xlsx'
  ];
  for(const fixture of fixtures) {
    const mimeType = await extractFileMimetype(fixture);
    console.log(fixture + ': ' + mimeType);
  }
}

testTypes().then(mimeType => {
  console.log('done.');
});
```
Outputs:
```
fixture.docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
fixture2.pptx: application/vnd.openxmlformats-officedocument.presentationml.presentation
fixture-vsdx.vsdx: application/vnd.ms-visio.drawing
fixture-vstx.vsdx: application/vnd.ms-visio.drawing
file_example_XLSX_10.xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
done.
```

**Comment by scottdoc** [comment]
This looks like this solution would work. The file I am testing with does have that content type xml file as expected. However, it is stored in s3 and it also appears to take a very long time for the tokenizer in the parse method to make its way to the `[Content_Types].xml` file entry. 

How would this code work with the tokenizer rather than reading the file from a drive? Or would the entire thing need to be downloaded?

Another thing, I noticed that when it gets to the `ppt/notesMasters/notesMaster1.xml` entry it does return the pptx type, but only because that entry happens to end in ".xml" - it skips all the others like `ppt/media/image25.svg`, `ppt/media/image16.jpeg`, etc.

**Comment by Borewit** [comment]
I explored the issue with unzipping further and identified potential improvements to the existing implementation in file-type. Specifically, the code that iterates over files in WinZip archives:

https://github.com/sindresorhus/file-type/blob/7e5686beccae38bfeb56a87dedf5ade1b62b676c/core.js#L501-L502

The current logic scans for the next WinZip header preamble when the compressed size is 0. Contrary to the comment, this behavior is not an error but is consistent with the ZIP specification when bit 3 of the _general purpose bit flag_ is set is set in the _local file header_. In such cases, the actual size of the data is written in the _data descriptor_ following the data chunk.[^1]

For example, Open Office XML (OOXML) documents often use this encoding style. This mode simplifies writing compressed streams by allowing the encoder to first write the data and append the length afterward. However, it complicates reading because the length is unknown until the data descriptor is encountered. This necessitates searching for the next header byte-by-byte, which is inefficient.

To optimize, the current implementation could possibly read larger chunks of data to speed up the header search. 

[^1]: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT, Section 4.3.9.1

**Comment by scottdoc** [comment]
Hi Borewit, 
Yes, I think you are correct. I also went down the path looking up zip standards and saw information on that 3rd bit, and also cases where zip64 is used. A correct implementation would likely need to skip to the end and read the file Central Directory which is positioned right at the end of zip files.

However, as you point out, a quick fix is updating the buffer size. I tested by using a bigger buffer size, multiplying the current by 100, and it went from 3m to 6s!

Unfortunately, the current code does not allow setting a custom buffer size since it uses the hard-coded value `reasonableDetectionSizeInBytes` which is set to 4100.

Perhaps rather than altering this or exposing it as an option, the parse method could increase the buffer if a zip file is detected?

**Comment by Borewit** [comment]
It’s not currently possible to start reading a file from the end within the existing architecture, as this approach is incompatible with how streams are processed.

> Perhaps rather than altering this or exposing it as an option, the parse method could increase the buffer if a zip file is detected?

I’m working on an improved implementation for handling ZIP files, which will include support for extracting specific content. As part of that, I will indeed use a dedicated larger buffer for that purpose.
