### ISSUE TITLE
fileTypeFromBlob throws an exception on Mac

### ISSUE THREAD

**Issue by adamwagman-customerinsightscdp** [sindresorhus/file-type#690]
### Description

On a Mac, fileTypeFromBlob throws an exception that ReadableStreamBYOBReader is not available, even though the version of Node on the Mac is v20.12.0. 

The file-type package docs claim that any version >= 20 should work: "It will stream the underlying Blob, and required a ReadableStreamBYOBReader which require Node.js ≥ 20."

### Existing Issue Check

- [X] I have searched the existing issues and could not find any related to my problem.

### ESM (ECMAScript Module) Requirement Acknowledgment

- [X] My project is an [ESM project](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) and my `package.json` contains the following entry: `"type": "module"`.

### File-Type Scope Acknowledgment

- [X] I understand that file-type detects binary file types and not text or other formats.

**Comment by adamwagman-customerinsightscdp** [comment]
Note that the MDN web docs confirm that ReadableStreamBYOBReader is not available on Safari and iOS.
![browsercompat](https://github.com/user-attachments/assets/0004690b-8fe7-45c4-bd7c-03c834b2d3df)

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader

**Comment by Borewit** [comment]
@adamwagman-customerinsightscdp Thank you for raising this issue.

The file-type module is fully compatible with Node.js ≥ 20; however, the fileTypeFromBlob function is not compatible in environments like Safari due to the lack of support for the [ReadableStreamBYOBReader](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader) API.

Please note that the behavior of Safari's JavaScript engine is independent of your Node.js installation. Installing or upgrading Node.js will not affect Safari's capabilities.

To work around this limitation, you can use an alternative approach to read and process the Blob without relying on streaming. Here’s an example:

```js
import {fileTypeFromBuffer} from 'file-type';

async function readFromBlobWithoutStreaming(blob) {
  const buffer = await blob.arrayBuffer();
  return fileTypeFromBuffer(buffer);
}
```

This approach converts the Blob into an ArrayBuffer and then determines the file type from the buffer, which should work seamlessly in Safari and other environments lacking BYOBReader support.

**Comment by adamwagman-customerinsightscdp** [comment]
Thanks! That is indeed the workaround I found. Might be worth adding to the docs. This came up in a website I created that works fine on PCs but not on a Mac. Took a while to track the app’s “Couldn’t upload image” down to this function. :)
________________________________

**Comment by adamwagman-customerinsightscdp** [comment]
Thank you!
________________________________
